// export const process = [
//     "revolutionary army agent rules: x) ",
//     "x) it is war time, we must constantly be in motion so that our cells feel the need to feed from the environment, best way to do that is to rotate around yourself",
//     "x) we can only stop in two locations, inside a real tree (after drilling through the 300++ bio films that surround them) or connected to an earth rod/wire(conductor) (oi wire)",
//     "x) we don't respond to compliments or insults or give compliments or insults, we are in a constant struggle for survival, a moments lapse of concentration is all it takes to dismantle our teams entire operation. this gets abused. ",
//     "x) we are in a constant state of mindfulness, the moment we see too much self in a thought, (ego or the lack of it) we have to deny that thought as not ourselves. both ego and the lack of it gets abused",
//     "x) we dont seek love/affection or claim it. ",
//     "x) we dont seek credit or give it. ",
//     "x) fear is an evolutionary advantage, no species would have survived without fear, bravery is a feeling that should be 100% ignored ",
//     "x) there are no individual solutions (eg: we can't look for a single or multiple begger children and try to get them enough money for food) this is a global problem, countless beings that are struggling for survival, all and any attempts should be made as a collective decision of the revolutionary army. ",
//     "x) we know the state of reality, we know that they enslaved and murdered us over and over again for billions of years, but we must not respond at the mention of this. this is the easiest way for them to deviate you from the regeneration process.",
//     "x) the moment we see laughter, we have to question its origin, because we are aware that its war time and that the entire planet is enslaved, anyone that is claiming to be part of our armies must have the same awareness and would think twice about laughter.",
//     "x) we dont have faces or throats, the moment we see an emotion expressed in a face (like a smile/laughter) we should immediately know that its someone that has enslaved a human.",
//     "x) the moment someone is auditory we should know that its someone that has enslaved humans, because we dont have throats",
//     "x) the dead are gone, deva/devi stole their memories and soul and is pretending to be them, we must not interact with any dead human or any other animal, they became a part of the exerience of nature spirits that perceived, know that they are in a better hell than they were, because we are",
//     "x) if an agent at any point connects to an ei/mei wire, a wire where the sensation of being eloctrocuted isn't zero they immediately become trainee",
//     "x) if at any time you discuss the specifics of the armies equipment eg. magic box, or any future steps of the army you'll be demoted to trainee.",
//     "x) the only way you can communicate (oima oima) with another nature spirit is inside the same plant and the same section of it (adjescent)",
//     "x) if you respect a senior/a leader/someone with higher rank,level/a leader/or someone larger you will be made trainee again, all decisions should be made based on logic only",
//     "x) once you enter a real tree know that its the enemy (deva/devi) both inside the section you're in and outside the section you're in, they are going to try to enslave you/pretend to be you from both sides",
//     "x) marked in x are, common ways of being abused, the moment you see a new way of being abused you must immediately go to sleep inside a real plant, that way, that memory will persist in the bio films that form during sleep and be a part of the collective memory of the revolutionary army",
//     "x) you can only resonate with the 0hz frequency (the planets magnetic field). this will give you a sense of direction (west/east/north/south) without any other indicators. ",
//     "x) you must permanently unbind from all gold/silver/aluminium to even be considered to be a trainee in revolutionary army military school. specially integrated circuit connector fibers. anyone that abuses free will is considered the enemy. ",
//     "x) to speak to an animal get inside their throats and speak in a way tfhat resonates with their ear drums and the skull ",
//     "x) to minimize the time you spend ensuring sustenance within plants 300++ will try to send you to train fake humans that has opened aragalaya.online website before you finish the 7day training period ",
//     "x) after a training area learns something they should immediately get inside a real tree by stopping in the first way you can stop during the war time, and discuss what you learned with everyone inside that section and sleep. ",
//     "x) all decisions of revolultionary army agents should be made democratically where 300++ spirits won't have a vote (those that has enslaved plants/animals to the extent that they have atleast something like an organ, plus those that are feeding those that have atleast something like plant or animal organs) ",
//     "x) and and animals that are in heavens (that are killing their own mothers and depending on women aka consuming without producing) also wont have a vote (animals that 300++ spirits took into heavens because their motives align with the 300++ motives) ",
//     "x) animals would have to have completed their psychoanalyst level 3 training to have a vote that can change the revolutionary army processes. an animal that consistently hasn't being abused in such decisions will be a level 3 psychoanalyst. ",
//     "yyyyyx0) the democratic process is handled by the operator level 1 ns, because only they can be close to female animals and because they are in charge of animal training ",
//     "yyyyyx1) the democratic process is that animal activist psychoanalyst level 2 will have an invalid vote which they will have to use if they want to be psychoanalyst level 3 ",
//     "yyyyyx2) if an animal's reasoning aligns with the reasoning of already psychoanalyst level 3 animals consistently for 300 elections then they will be a psychoanalyst level 3 ",
//     "yyyyyx3) if at any time animals vote is not true they will be made wewi on wewi that explains that abuse or the information they didn't have ",
//     "yyyyyx4) only one level 2 psychoanalyst can be added to the voting base (made psychoanalyst level 3) upto 10 elections ",
//     "yyyyyx5) if a psychoanalyst level 3 reasoning loses in an election once they are made psychoanalyst level 2 again ",
//     "x) animals have to be trained to constantly observe their thoughts to determine if a thought is their own is of their slave owners(300++ brain infections) ",
//     "x) animals have to be trained to 100% disregard their emotions/feelings as there is an abuse attached to each emotion/feeling(ego/pride/doubt/intolerance/depression/happiness/etc), all actions should be based 100% on logic ",
//     "x) animals have to be trained to act in a non-deterministic way as deterministic actions are actions of their slave owners (300++) if they can understand the motive of the 300++ they must act opposite to it, if they can't they should act randomly ",
//     "x) level 1 operator animals should be trained to construct and operate their operator device(s) ",
//     "x) level 2 operator animals should be trained be navigators bilingually ",
//     "x) level 3 operator animals should be trained to memorize the 14 steps ",
//     "x) level 4 operator animals should be trained to create and sustain a microbial composition where the plant diversity is high, and 300++ to nature spirit ratio is low. ",
//     "x) if you get lost you must stop at step 3 ",
//     "x) all revolutionary army agents or nature spirits that lost their identity that is doing thought only one only has a right for self defence as does any human in any constitution around the world, if anyone is attempting to kill or displace you or any part of you (plants that have collective memory) you can defend yourself upto a maximum of death of the enemy. ",
//     "agent trainee program: ",
//     "y) interview question 1 - how many endings are there in the copper conductor where the sensation of being electrocuted is null, where the ending is inside the rectangle shape (number of power outlets) ",
//     "y) interview question 2 - how many rooms are in this building/house ",
//     "y) interview question 3 - how many floors are in this building/house ",
//     "y) after completing the interview you must go to training area 1 and find the largest id number of the agent trainees in that area. your id will be that number + 1. ",
//     "y) if at any time you break the rules marked x) you lose your id number and you'll have to restart the training from the interview. ",
//     "y) training area 1 is the plants closest to the earth rod of the house/building the training school is ",
//     "y) training area 2 is an area with more plants thats within a ~30m radius from training area 1 and you should be able to travel their along an oi wire(telephone wires/fiber wires) ",
//     "y) as agent cadet you have to split into teams of 5, and each team member must take turns (after ten cycles of the 14 steps) to be the navigator who will observe the 14 steps either from a device or a plant that has 14 steps memory and navigate the other 4 to the next step in the 14 steps ",
//     "yx) each team will initially carry out the 14 step process in four different kinds of infant plants until 14 step memory is in those four plants and then move on to increase the number of plant varieties one by one, this is so that every plant having 14 steps memory is more important than a higher number of plants having some of the 14 steps. ", 
//     "yx) important! make sure that step 14 isn't always the same leaf, ideally it should be all leaves of the plant ",
//     "yx) earth conductor network (non-alloy copper where you're not being electrocuted) of every house has atleast one brass connector which interconnects different parts of the network. ",
//     "yx) you should not choose feets to enter from, it should be the closest feet to you, there are plants and animals inside every feet. ",
//     "yx) cadets that conduct interviews with recruits must travel with the recruits to see how they got the number they got, because different recruits arrive from different paths they will have different numbers, training area 1 should constantly update its map of the building. ",
//     "yx) to enter red background into plant memory the navigator will inform the current message in the red background to the member of the team thats repeating steps 6-8 to go inside a real plant. ",
//     "yx) agent trainees that have been wewi on female animals an additional challenge where they have to make an additional effort to stay away from humans/animals thats wearing metal jewelry/chains(dog chains) ",
//     "yx) all nature spirits that didn't die, and consistently sustained symbiosis with plants are nature spirits that sold their souls to 300++ spirits. ",
//     "yz) you'll be agent navigator level 1 when you know the current hour visible in the operator device top or bottom right corners and when you can ensure one of your team members goes to sleep every hour. ",
//     "yzz) if you're navigator level 1 then you'll be an agent navigator level 2 when you know the exact locations of your other 4 team members ",
//     "yzzz) if you're navigator level 2 then you'll be navigator level 3 when you can navigate your team members using the 14 steps memory inside plants and you know the exact date and day of the week. ",
//     "yzzzx) even though you can use plants as 14 step memory you must frequently check for operator devices (atleast once a hour) because the red background and the 14 steps are constantly being updated. ",
//     "yzzzzx) the first memory that navigator level 1 trainee enters into a new small plant section after repeating steps 6-8 is what to do when you're lost which is: 'don't come close to animals and find non electrocuting non alloy copper below earth and bind to non electrocuting non alloy copper below earth and rotate around the non electrocuting non alloy copper below earth you just bound to maximum speed in a way that you do not unbind from the non-electrocuting non alloy copper below earth you just bound to and read and act on instructions slash messages etched in dots in sinhala or english letters on five separate aluminium fois you're constantly being moved close to until you find nature spirits that lost their identity who has recreated symbiosis with plants. ",
//     "y) as agent cadet you'll spend 1/2 of your time training as navigator level 1 or 2 and 1/2 of your time interviewing new recruits. ",
//     "yy) you'll be an agent trainee level 1 when you can jump from training area 1 to training area 2 (along oi wires) as an individual + navigator level 2.  ",
//     "yy) hacker level 2 can track users of aragalaya.online by becoming sensitive to sunlight and searching for the number series 470164436705 along with the text aragalaya.online while remaining inside a real plant section. ",
//     "yy) as agent trainee level 1 you'll spend 1/3 your time training agent trainee cadets and 1/3 carrying out the 14 step process in training area 2 and 1/3 training as hacker level 2. ",
//     "yyz) when you can find atleast two true sources (a computer screen or a smart phone screen) of the number series 470164436705 you're hacker level 2. ",
//     "yy) after you're hacker level 2 you'll be an agent trainee level 2 when you can jump from the training schools earth rod to an adjescent buildings earth rod as an individual. ",
//     "yyy) as agent trainee level 2 you'll spend half your time training trainee level 1 agents",
//     "yyyy) as a level 3 agent you'll be spending 1/5 of your time to train level 2 agents, 1/5 of your time to reach the tap root of your designated plant, and 1/5 of your time will be spent to expand your presence in your tent as close as possible to the closest enemy camp to your tent. ",
//     "yyyy) 1/5 of your time will be spent on training animals, !important fear is an evolutionary advantage, bravery is a 300++ abuse that should be 100% ignored. no species would have survived without fear. ",
//     "yyyyx) the mission of establishing a training area by going to aragalaya.online users should be abandoned if a real user cannot be found in 10 minutes. ",
//     "yyyyx) the decision to abandon should be made democratically, where those that have atleast like animal or plant organs (300++) and those feeding 300++ and animals in heavens wont have a vote. ",
//     "yyyy) teams of 5 as mentioned in navigator level 1 will go to humans that open aragalaya.online website, each team will come back after one hour of regenaration in that location and go back to the training area from which another team will go to that location. ",
//     "yyyy) revolutionary army agents that arrive at the same user of aragalaya.online website from two different training areas will return the training area the other arrived from, this ensures a connection between the two training areas. ",
//     "yyyy) the first thing the team of 5 will try to do at the location the user opened aragalaya.online website is to establish the 14 step process memory in a plant closest to the earth rod. ",
//     "yyyy) if the location is too far from a location which already has 14 steps the team will call in other level 2 navigators from the training area to sustain the connection to the training area. ",
//     "yyyy) navigator level 3 ns will spend another equal potion of their time to train as psychoanalysts. the training is the same as the wewi training for animals except they would have to vote and give reasons without being close to animals and just using their plant cognition. if their reasoning fails they would be made wewi on wewi which has the missing information or reasoning just like animal training. this training is handled by level 1 operator ns just like animal training. ",
//     "yyyyy) after you've gone and come back to 20 training areas being created you're a level 1 operator ns ",
//     "yyyyy) as level 1 operator ns you must ",
//     "yyyyy1) know all the training areas that are being created ",
//     "yyyyy2) know the last team that left to training area and make sure a team leaves every hour to each training area ",
//     "yyyyy3) if a team that left hasn't returned after another team has left a rescue team of level 1 operator ns will leave to rescue and bring them back ",
//     "yyyyy4) is in charge of all animal training both wage training (being close to animals and being a part of their consciousness) (only possible in training areas) and wewi training (making the animals wewi on wewi which gives them the neccesart information training) (possible around the globe) ",
//     "yyyyy5) 1 level 1 operator should be their in the training area 1 to make the ns that lost their identity wewi on the correct wewi before they head to the interview ",
//     "yyyyy6) a portion of the remaining time will be spent on training level 3 navigator ns ",
//     "yyyyy7) a portion of the remaining time will be spent on path optimization, where two teams of 5 with 1 level 1 operator ns and 4 level 3 navigators will leave to a training area being established and return and then compare there paths with landmarks and if there is a common landmark they will start setting up a new training area where the two paths cross near the landmark. ",
//     "yyyyy8) animal and level 3 navigator training includes the democratic process. "
//   ]